# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

# image will be published to ghcr.io/<user>/<name>
name: leos
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: justfiles
    validate: true
    include:
      - chezmoi.just
      - flatpaks.just

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/repo/fedora-%OS_VERSION%/ryanabx-cosmic-epoch-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/wiiznokes/cosmic-applets-unofficial/repo/fedora-%OS_VERSION%/wiiznokes-cosmic-applets-unofficial-fedora-%OS_VERSION%.repo
    install:
      - openrgb-udev-rules
      - openssl
      - cryfs
      - rclone
      - ptyxis
      - zsh
      - neovim
      - ripgrep
      - fzf
      - wl-clipboard
      - xclip
      - flatpak-builder
      - cosmic-desktop
      - cosmic-ext-applet-clipboard-manager
      - adw-gtk3-theme
      - rsms-inter-fonts
      - https://code.visualstudio.com/sha/download?build=stable&os=linux-rpm-x64
    remove:
      - firefox
      - firefox-langpacks

  - type: gschema-overrides
    include:
      - zz1-adw-gtk3.gschema.override
      - zz1-inter.gschema.override
      - zz1-ptyxis.gschema.override

  # - type: systemd
  #   system:
  #     disabled:
  #       - gdm
  #     enabled:
  #       - cosmic-greeter

  - type: bling
    install:
      - 1password

  - type: script
    scripts:
      - install_remnote.sh
      - install_zed.sh

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono

  - type: chezmoi
    all-users: false
    disable-init: true

  - type: signing
