# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: leos
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bluefin-nvidia-open
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: justfiles
    validate: true
    include:
      - distrobox.just

  - type: default-flatpaks
    configurations:
      - scope: user
        repo:
          title: Flathub (user)
      - scope: user
        repo:
          title: Flathub (beta)
          url: https://flathub.org/beta-repo/flathub-beta.flatpakrepo
      - scope: system
        repo:
          title: Flathub (system)
        install:
          - ca.desrt.dconf-editor
          - com.github.tchx84.Flatseal
          - io.github.flattool.Ignition
          - io.github.flattool.Warehouse
          - it.mijorus.gearlever
          - com.dec05eba.gpu_screen_recorder
          - net.nokyan.Resources
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Contacts
          - org.gnome.Decibels
          - org.gnome.FileRoller
          - org.gnome.Firmware
          - org.gnome.Loupe
          - org.gnome.Maps
          - org.gnome.Papers
          - org.gnome.Showtime
          - org.gnome.Snapshot
          - org.gnome.TextEditor
          - org.gnome.baobab
          - org.gnome.clocks

  - type: dnf
    repos:
      copr:
        - yalter/niri-git
        - ulysg/xwayland-satellite
        - errornointernet/quickshell
        - scottames/ghostty
        - gvalkov/vicinae
        - errornointernet/walker
        - ublue-os/packages # for bazaar
    install:
      install-weak-deps: false
      packages:
        # Basics
        - openrgb-udev-rules
        - openssl
        - cryfs
        - chezmoi
        # Terminal
        - kitty
        - ghostty
        - zsh
        - nu
        - ripgrep
        - lsd
        - bat
        - fd-find
        - fzf
        - zoxide
        # Neovim
        - neovim
        - tree-sitter-cli
        - xsel
        - wl-clipboard
        - xclip
        - inotify-tools
        - luarocks
        - nodejs
        - nodejs-npm
        # Nautilus Plugins
        - nautilus-python
        - python3-dbus
        # Niri
        - niri
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-gnome
        - gnome-keyring
        - xrdb
        - xwayland-satellite
        - mate-polkit
        - brightnessctl
        - greetd-selinux
        - greetd
        - gtkgreet
        - quickshell-git
        - wlsunset
        - bazaar
        - vicinae
        - elephant
        - walker
        # Styling
        - darkman
        - gnu-free-mono-fonts
        - adw-gtk3-theme
        - breeze-icon-theme
        - plasma-breeze
        - qqc2-breeze-style
        - qt6ct
        # Profiling
        - sysprof
        # Development
        - flatpak-builder
        # Android
        - kde-connect
        - kde-connect-nautilus
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: gschema-overrides
    include:
      - zz1-adw-gtk3.gschema.override

  - type: bling
    install:
      - 1password

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - AdwaitaMono

  - type: script
    scripts:
      - install-noctalia-shell.sh
      - install-noctalia-greet.sh

  - type: systemd
    system:
      disabled:
        - gdm
      enabled:
        - greetd

  - type: signing
