# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

# image will be published to ghcr.io/<user>/<name>
name: leos
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: justfiles
    validate: true
    include:
      - chezmoi.just
      - flatpaks.just

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/errornointernet/walker/repo/fedora-%OS_VERSION%/errornointernet-walker-fedora-%OS_VERSION%.repo
    install:
      # Basics
      - openrgb-udev-rules
      - openssl
      - cryfs
      # Terminal
      - kitty
      - zsh
      - neovim
      - luarocks
      - ripgrep
      - fd-find
      - fzf
      - wl-clipboard
      - xclip
      - zoxide
      - nautilus-python
      - flatpak-builder
      # Hyprland
      - hyprland
      - hyprland-devel
      - xdg-desktop-portal-hyprland
      - hyprpaper
      - hyprsunset
      - hyprlock
      - hyprpolkitagent
      - waypaper
      - dunst
      - xrdb
      - walker
      # General Styling
      - darkman
      - rsms-inter-fonts
      # GTK Styling
      - adw-gtk3-theme
      # QT styling
      - breeze-icon-theme
      - plasma-breeze
      - qqc2-breeze-style
      - qt6ct
    remove:
      - firefox
      - firefox-langpacks

  - type: gschema-overrides
    include:
      - zz1-adw-gtk3.gschema.override
      - zz1-inter.gschema.override
      - zz1-ptyxis.gschema.override

  # - type: systemd
  #   system:
  #     disabled:
  #       - gdm
  #     enabled:
  #       - cosmic-greeter

  - type: bling
    install:
      - 1password

  - type: script
    scripts:
      - install_remnote.sh

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono

  - type: chezmoi
    repository: "git@codeberg.org:luleyleo/chezmoi.git"
    all-users: false
    disable-init: true
    disable-update: true

  - type: signing
