# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

# image will be published to ghcr.io/<user>/<name>
name: leos
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/repo/fedora-%OS_VERSION%/ryanabx-cosmic-epoch-fedora-%OS_VERSION%.repo
    install:
      - openrgb-udev-rules
      - openssl
      - ptyxis
      - zsh
      - neovim
      - ripgrep
      - fzf
      - cosmic-desktop
      - adw-gtk3-theme
      - rsms-inter-fonts
    remove:
      - firefox
      - firefox-langpacks

  # - type: systemd
  #   system:
  #     disabled:
  #       - gdm
  #     enabled:
  #       - cosmic-greeter

  - type: bling
    install:
      - 1password

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub-system
      repo-title: "Flathub (system-wide)"
      install:
        - org.mozilla.firefox
        - org.mozilla.Thunderbird
        - org.gnome.Loupe
        - org.gnome.Calendar
        - org.gnome.Contacts
        - org.gnome.baobab
        - org.gnome.Papers
        - org.gnome.TextEditor
        - org.fedoraproject.MediaWriter
        - it.mijorus.gearlever
        - com.github.tchx84.Flatseal
        - io.gitlab.news_flash.NewsFlash
        - com.nextcloud.desktopclient.nextcloud
        - org.onlyoffice.desktopeditors
        - org.openrgb.OpenRGB
        - com.github.jeromerobert.pdfarranger
        - net.nokyan.Resources
        - org.signal.Signal
        - com.spotify.Client
        - com.teamspeak.TeamSpeak
        - io.github.flattool.Warehouse
        - md.obsidian.Obsidian
      remove:
        - org.gnome.eog
    user:
      repo-url: https://dl.flathub.org/beta-repo/flathub-beta.flatpakrepo
      repo-name: flathub-beta
      repo-title: "Flathub Beta (user)"
      install:
        - org.zotero.Zotero

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono

  - type: chezmoi
    all-users: false
    disable-init: true

  - type: signing
