# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: leos
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bluefin-nvidia-open
image-version: 43

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: justfiles
    validate: true
    include:
      - distrobox.just

  - type: default-flatpaks
    configurations:
      - scope: user
        repo:
          name: flathub
          title: Flathub (user)
      - scope: user
        repo:
          name: flathub-beta
          title: Flathub (beta)
          url: https://flathub.org/beta-repo/flathub-beta.flatpakrepo
      - scope: system
        repo:
          name: flathub-system
          title: Flathub (system)
        install:
          - ca.desrt.dconf-editor
          - com.github.tchx84.Flatseal
          - io.github.flattool.Ignition
          - io.github.flattool.Warehouse
          - it.mijorus.gearlever
          - com.dec05eba.gpu_screen_recorder
          - net.nokyan.Resources
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Contacts
          - org.gnome.Decibels
          - org.gnome.FileRoller
          - org.gnome.Firmware
          - org.gnome.Loupe
          - org.gnome.Maps
          - org.gnome.Papers
          - org.gnome.Showtime
          - org.gnome.Snapshot
          - org.gnome.TextEditor
          - org.gnome.baobab
          - org.gnome.clocks

  - type: dnf
    group-install:
      with-optional: true
      packages:
        - virtualization

  - type: dnf
    repos:
      copr:
        - yalter/niri
    install:
      install-weak-deps: false
      packages:
        - gnome-keyring
        - xdg-desktop-portal-gnome
        - xdg-desktop-portal-gtk
        - wireplumber
        - niri

  - type: dnf
    repos:
      copr:
        - yalter/niri
        - avengemedia/dms
        - scottames/ghostty
        - scottames/vicinae
        - ublue-os/packages # for bazaar
    install:
      install-weak-deps: true
      packages:
        # Basics
        - openrgb-udev-rules
        - openssl
        - chezmoi
        # Terminals
        - kitty
        - ghostty
        # Shells
        - zsh
        - nu
        # Nautilus Plugins
        - nautilus-python
        - python3-dbus
        # Niri
        - xrdb
        - mate-polkit
        - vicinae
        - nodejs # required for Vicinae extensions
        # DMS
        - greetd
        - greetd-selinux
        - gammastep
        - brightnessctl
        - dms
        - dms-greeter
        # Clipboard Tools
        - xsel
        - wl-clipboard
        - cliphist
        - wtype
        # Styling
        - darkman
        - gnu-free-mono-fonts
        - adw-gtk3-theme
        - breeze-icon-theme
        - plasma-breeze
        - qqc2-breeze-style
        - qt6ct
        # Profiling
        - sysprof
        # Development
        - flatpak-builder
        - foundry
        # Android
        - kde-connect
        - kde-connect-nautilus
        # App Store
        - bazaar
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: script
    scripts:
      - install-app2unit.sh

  - type: copy
    from: build-source-apps
    src: /out/bin/niri-float-sticky
    dest: /usr/bin/

  - type: brew
    nofile-limits: true
    brew-analytics: false

  - type: gschema-overrides
    include:
      - zz1-adw-gtk3.gschema.override
      - zz1-adwaita-font.gschema.override

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - AdwaitaMono

  - type: systemd
    system:
      disabled:
        - gdm
      enabled:
        - greetd

  - type: signing

stages:
  - name: build-source-apps
    from: ghcr.io/ublue-os/base-main:43
    modules:
      - type: dnf
        install:
          packages:
            - golang
      - type: script
        snippets:
          - mkdir -p /out/bin
          - env GOBIN=/out/bin go install github.com/probeldev/niri-float-sticky@latest
          - strip /out/bin/niri-float-sticky
