# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: leos
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: justfiles
    validate: true
    include:
      - flatpaks.just
      - distrobox.just

  - type: dnf
    repos:
      copr:
        - yalter/niri
        - ulysg/xwayland-satellite
        - errornointernet/walker
        - erikreider/SwayNotificationCenter
        - tswsl1989/tswsl-wayland-extras # for gtklock
        - pgdev/ghostty
    install:
      packages:
        # Basics
        - openrgb-udev-rules
        - openssl
        - cryfs
        # Terminal
        - kitty
        - ghostty
        - zsh
        - ripgrep
        - lsd
        - bat
        - fd-find
        - fzf
        - wl-clipboard
        - xclip
        - zoxide
        # Neovim
        - neovim
        - luarocks
        # Nautilus Plugins
        - nautilus-python
        - python3-dbus
        # Niri
        - niri
        - waybar
        - swaylock
        - swaybg
        - swayidle
        - SwayNotificationCenter-git
        - xrdb
        - walker
        - xwayland-satellite
        - polkit-kde
        - greetd-selinux
        - greetd
        - gtkgreet
        - gtklock
        # General Styling
        - darkman
        - rsms-inter-fonts
        # GTK Styling
        - adw-gtk3-theme
        # QT styling
        - breeze-icon-theme
        - plasma-breeze
        - qqc2-breeze-style
        - qt6ct
        # Profiling
        - sysprof
        # Development
        - flatpak-builder
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: gschema-overrides
    include:
      - zz1-adw-gtk3.gschema.override
      - zz1-inter.gschema.override

  - type: bling
    install:
      - 1password

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - AdwaitaMono

  - type: systemd
    system:
      disabled:
        - gdm
      enabled:
        - greetd

  - type: chezmoi
    repository: "git@codeberg.org:luleyleo/chezmoi.git"
    all-users: false
    disable-init: true
    disable-update: true

  - type: signing
